vault_version: 1.14.0
vault_user: vault
vault_group: vaultg
vault_binary: /bin
vault_cfg: /etc/vault/vault.hcl
vault_service: /etc/systemd/system/vault.service 
unseal_keys_dir_output: .
root_token_dir_output: .
vault_initialized_process: false
vault_operation: uninstall


consul_cfg: /etc/consul/consul.json
consul_service: /etc/systemd/system/consul.service
consul_binary: /bin
consul_operation: install