---
    - name: Install Mysql on Debian
      ansible.builtin.apt:
         name: mysql-server
         state: present
      when: ansible_os_family == "Debian"
    - name: Install Mysql on RedHat
      ansible.builtin.yum:
         name: mysql-server
         state: present
      when: ansible_os_family == "RedHat"
    - name: Install java 11 on Debian
      ansible.builtin.apt:
         name: openjdk-11-jdk
         state: present
      when: ansible_os_family == "Debian"
    - name: Install java 11 on RedHat
      ansible.builtin.yum:
         name: openjdk-11-jdk
         state: present
      when: ansible_os_family == "RedHat"
    - name: Install tomcat on Debian
      ansible.builtin.apt:
         name: tomcat9
         state: present
      when: ansible_os_family == "Debian"
    - name: Install tomcat on RedHat
      ansible.builtin.yum:
         name: tomcat9
         state: present
      when: ansible_os_family == "RedHat"
    - name: Create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        groups: tomcat
      notify:
        - Restart tomcat