apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
  annotations:
    kubernetes.io/change-cause: "Deploy shopping version 2"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  replicas: 7
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: dash04/shopping:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30007