version: '3.1'

services:
  attendance:
    image: dash04/attendance:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql
    volumes:
      - config:/app/config
    env_file:
      - attendance.env
    environment:
      MYSQL_HOST: mysql
    networks:
      - ot-ntw

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: your_database_name
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ot-ntw

volumes:
  mysql-data:
  config:

networks:
  ot-ntw:
    driver: bridge