#!/bin/bash
# Update the package repository and install Nginx
sudo apt update -y
sudo apt install nginx -y

# Start Nginx
sudo service nginx start

# Enable Nginx to start on boot
sudo systemctl enable nginx

sudo apt install stress -y