pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                sshagent(['ansible-server']) {
                
                sh 'ssh -o StrictHostKeyChecking=no ubuntu@${batianIp}'
                sh 'scp setup-ansible/* ubuntu@${batianIp}:/home/ubuntu/'

                }
            }
        }
    }
}
