apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Changing nginx latest versionn to custom image"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dogra21703/ninja21:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name:  nginx-nodeport
spec:
  selector:
    app:  nginx
  type:   NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80