---
plugin: aws_ec2

regions:
  - ap-south-1

keyed_groups:

  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable.

  - key: tags.Ansible

    prefix: tag_Name_

    separator: ""

keyed_groups:
  ubuntu_servers: "'ubuntu' in tag_Distribution"
  redhat_servers: "'redhat' in tag_Distribution"

compose:
  ansible_host: private_ip_address