version: '3'
services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - 8200:8200
    volumes:
      - ./config:/vault/config
      - ~/vault:/vault/logs
    command: server
    networks:
      - vault-net
    cap_add:
      - IPC_LOCK

networks:
  vault-net:
